### ISSUE TITLE
How to run detectron2_mscoco_proposal_maxnms.py with multiple gpus?

### ISSUE THREAD

**Issue by Jack-lx-jiang** [airsplay/py-bottom-up-attention#12]
Hi,

I am new to detectron2. I want to extract the feature with multi-gpu, but it seems detectron2_mscoco_proposal_maxnms.py only uses 1 gpu. 

Could you give me some guidance how to run detectron2_mscoco_proposal_maxnms.py with multiple gpus?

Looking forward to your reply.

**Comment by airsplay** [comment]
I am not sure about whether D2 supports multi-gpu or not, but you could launch the extraction script on 4 GPUs separately.

**Comment by Jack-lx-jiang** [comment]
> I am not sure about whether D2 supports multi-gpu or not, but you could launch the extraction script on 4 GPUs separately.

That could be an alternative solution. Thanks for your advice.
