### ISSUE TITLE
What is the JSON file "coco_minival_img_ids.json"?

### ISSUE THREAD

**Issue by liuyyy111** [airsplay/py-bottom-up-attention#17]
Hi, thanks for your share.
And i don't know what is the file "coco_minival_img_ids.json" when i extracted features from 'val2014'.

so, how can i get the file

can you provide it? or how can i generate it

**Comment by airsplay** [comment]
It comes from this file `https://nlp1.cs.unc.edu/data/lxmert_data/lxmert/mscoco_minival.json`, could be downloaded with `wget --no-check-certificate https://nlp1.cs.unc.edu/data/lxmert_data/lxmert/mscoco_minival.json -P data/lxmert/
` and processed with 

```python
data = json.load(open("mscoco_minival.json"))
img_ids = [datum['img_id'] for datum in data]
```

**Comment by liuyyy111** [comment]
Thank you for your prompt reply
