### ISSUE TITLE
WARNING [01/11 17:21:52 d2.config.compat]: Config '/home/lvxinyu/AVVP/Others/py-bottom-up-attention/configs/VG-Detection/faster_rcnn_R_101_C4_caffe.yaml' has no VERSION. Assuming it to be compatible with latest v2. Modifications for VG in RPN (modeling/proposal_generator/rpn.py): 	Use hidden dim 512 instead fo the same dim as Res4 (1024).  Modifications for VG in RoI heads (modeling/roi_heads/roi_heads.py): 	1. Change the stride of conv1 and shortcut in Res5.Block1 from 2 to 1. 	2. Modifying all conv2 with (padding: 1 --> 2) and (dilation: 1 --> 2). 	For more details, please check 'https://github.com/peteanderson80/bottom-up-attention/blob/master/models/vg/ResNet-101/faster_rcnn_end2end_final/test.prototxt'.

### ISSUE THREAD

**Issue by XinyuLyu** [airsplay/py-bottom-up-attention#18]
Hi! When I run the demo_vg_detection.ipynb, it has such logs without predicted results. Can you help me with that?

WARNING [01/11 17:21:52 d2.config.compat]: Config '/home/lvxinyu/AVVP/Others/py-bottom-up-attention/configs/VG-Detection/faster_rcnn_R_101_C4_caffe.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Modifications for VG in RPN (modeling/proposal_generator/rpn.py):
	Use hidden dim 512 instead fo the same dim as Res4 (1024).

Modifications for VG in RoI heads (modeling/roi_heads/roi_heads.py):
	1. Change the stride of conv1 and shortcut in Res5.Block1 from 2 to 1.
	2. Modifying all conv2 with (padding: 1 --> 2) and (dilation: 1 --> 2).
	For more details, please check 'https://github.com/peteanderson80/bottom-up-attention/blob/master/models/vg/ResNet-101/faster_rcnn_end2end_final/test.prototxt'.

**Comment by airsplay** [comment]
Thanks.

I think that the reason might be a slow speed in downloading the weights. Could you help test whether you could download the weight file `http://nlp.cs.unc.edu/models/faster_rcnn_from_caffe.pkl` locally? If so, you could edit the line
```
cfg.MODEL.WEIGHTS = "http://nlp.cs.unc.edu/models/faster_rcnn_from_caffe.pkl"
```
with this local downloaded location and it should work fine now.

Best,
Hao

**Comment by XinyuLyu** [comment]
I have tried it, but still not work.

**Comment by airsplay** [comment]
I do not think that these modifications to py would cause a problem.

Btw, the current return message is a WARNING which says that the version of configuration is not specified. This WARNING would not cause an issue in other processing steps.
Have you encountered any other issues when you proceed with this script?

I encourage you to test with the original ipynb once to see whether the outputs are successfully printed. It should work without CUDA as well.
