### ISSUE TITLE
Converting the output tensor which is a Detectron 2 tensor to a normal PyTorch tensor

### ISSUE THREAD

**Issue by monajalal** [airsplay/py-bottom-up-attention#9]
How can I convert the Detectron 2 output tensors to normal PyTorch tensors?

I am sharing the results with someone who doesn't and can't install Detectron2 on his machine due to limitations and wonder how I could convert them to normal PyTorch tensors?

I have to set of .pt files one of them is the ROI extracted features for 36 ROIs in the image

and the other one is the .pt relating to bounding boxes, their prediction, and class number.

![detectron2_ft](https://user-images.githubusercontent.com/1892917/85422174-4ac3be80-b543-11ea-8714-50925dcf655a.png)
![detectron2_tensors](https://user-images.githubusercontent.com/1892917/85422177-4b5c5500-b543-11ea-80bb-cf60b6ca3875.png)

The person is also able to use them in Google Colab but didn't find an easy installation of your code or detectron 2 for Google Colab.

**Comment by airsplay** [comment]
It might be converted to the python dict by using 
```python
result = {
'pred_boxes': prd.pred_boxes,
...
}
```

The colab of Detectron2 could be found [here](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) in the original [D2 repo](https://github.com/facebookresearch/detectron2). 

However, I might not be such lucky that I indeed have not successfully installed D2 on colab before...
